language: php

php:
  - 7.3
  - 7.4

os: linux

services:
  - mysql

before_script:
  - cp .env.example .env
  - sudo mysql -e 'create database parker_test;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
